### ISSUE TITLE
Automatically start browser when running tests

### ISSUE THREAD

**Issue by lpil** [HashNuke/hound#30]
Hello!

I think it would be handy is hound automatically started a browser if one wasn't already running. :)

Cheers,
Louis

**Comment by HashNuke** [comment]
There's a recent PR by @manukall. I was waiting to rework Hound's internals before looking into it. Just published a new version. I'll finish add this feature this week.

**Comment by lpil** [comment]
Thank you!

**Comment by rockwood** [comment]
Any updates on this? It would be great if hound automatically started/stopped web drivers. Would it be helpful for me put together another PR?

**Comment by HashNuke** [comment]
I've merged @manukall's PR. That auto-starts phantomjs. Selenium takes a while to start. Detecting if it's started/ready requires a recursive function. Feel free to give this a shot.

**Comment by rockwood** [comment]
Great. Thank you!

**Comment by HashNuke** [comment]
Removed this feature in the recent release (0.7.6) since it started on the path of patches to fix starting phantomjs. That'll be the same for other browsers. Overtime we'll start on a detour to make releases just to fix these errors.
Anyone who wants to author a lib that auto-starts browsers is welcome and I'll link to it on the readme.
